report:
  settings:
    page:
      size: LETTER
      orientation: P
      #margins: [45, -1, 45, -1]
      numbering:
        position: top
        align: right
        offset: 0
  body:
    1:
      image:
        filename: header.png
        align: center
    2:
      text:
        field: subtitle
        align: center
        spacing: 1.5
        font:
          size: 10
          color: [70, 70, 70]
    3:
      table:
        field: data
        borders: none
        heading:
          align: center
          bold: true
        columns:
          codigo:
            label: Codigo debe ser una etiqueta muy muy larga
            align: center
            width: 100
          nombre:
            label: Nombre
            align: left
            width: 200
        font:
          size: 10
          color: [0, 0, 0]
    4:
      text:
        field: footer
        align: center
    5:
      text:
        field: popo
        align: left
