reporte:
  filename: reporte-detallado-compras.pdf
  page:
    size: Letter
    margins: 15
    orientation: P
  
  header:
    image:
      path: header_reporte.png
      width: 190
      height: 25
      x: 13
      y: 10
      separator: 23
    title: Detalle de Compras de Cafe Verde
    style: 
      font: [Arial, B, 14]
      forecolor: [0, 0, 0]
      align: C
  
  body:
    header:
      style: 
        font: [Arial, ~, 10]
        forecolor: [0, 0, 0]
        bgcolor: [220, 220, 220]
        align: C
        border: TB
    columns:
      1:
        label: Fecha
        field: fecha
        style: 
          align: C
          width: 20
      2:
        label: Factura
        field: numero
        style: 
          align: C
          width: 20
      3:
        label: Productor
        field: productor
        style: 
          align: L
          width: 50
      4:
        label: C.I.
        field: cedula
        style: 
          align: R
          width: 15
      5:
        label: QQ
        field: cantidad
        sum: Y
        precision: 2
        style: 
          align: R
          width: 15
      6:
        label: Total BsF
        field: monto
        sum: Y
        precision: 2
        style: 
          align: R
          width: 25
      7:
        label: Chequera
        field: chequera
        style: 
          align: R
          width: 20
      8:
        label: Cheque
        field: cheque
        style: 
          align: R
          width: 25
          
    grouping:
      1:
        label: UAPSS
        field: uapss
        style:
          font: [Arial, B, 9]
          forecolor: [0, 0, 75]
          border: B
          margin: 3
    
    subtotal:
      apply: Y
      label: Subtotal
      style: 
        font: [Arial, B, 9]
        bgcolor: [220, 220, 220]
        border: TB
    
    total:
      apply: N
      label: TOTAL
      style: 
        font: [Arial, B, 9]
        bgcolor: [220, 220, 220]
        border: TB
      
  footer:
    label: Desarrollado por la Gerencia de Ciencia y Tecnologia de CVA Cafe (C) Copyleft 2009
    style: 
      forecolor: [40, 40, 180]
      align: C
    
