report:
  settings:
    page:
      size: Letter
      orientation: L
      margins: 20
    style:
      font_family: 'Helvetica'
      font_size: 10
      font_color: [0, 0, 0]
  header:
    1:
      text:
        label: INVERSIONES PORCINAS C.A.
        margin: 30
        align: left
        style:
          font_size: 11
          font_weight: B
    2:
      text:
        label: "RIF: 0-00000000-0"
        margin: 30
        align: left
        style:
          font_size: 10
    3:
      image:
        filename: default-report-logo.png
        width: 20
        height: 20
        x: 20
        y: 12
    4:
      text:
        label: Yaritagua - Estado Yaracuy
        margin: 30
        align: left
        style:
          font_size: 10
    5:
      breakline:
    6:
      pagenum:
        pattern: "Pag. <PAGE>"
        align: right
  body:
    1:
      text:
        label: "Orden: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    2:
      text:
        field: order
        align: left
        width: 50
    3:
      text:
        label: "Formula: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    4:
      text:
        field: recipe
        align: left
        width: 50
    5:
      text:
        label: "Prod. Term.: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    6:
      text:
        field: product
        align: left
        width: 50
    7:
      text:
        label: "Inicio: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    8:
      text:
        field: start_date
        align: left
        width: 50
    9:
      text:
        label: "Final: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    10:
      text:
        field: end_date
        align: left
        width: 50
    11:
      text:
        label: "Batch Prog.: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    12:
      text:
        field: prog_batches
        align: left
        width: 13
        breakline: 0
    13:
      text:
        label: "Batch Real.: "
        align: right
        width: 25
        breakline: 0
        style:
          font_weight: B
    14:
      text:
        field: real_batches
        align: left
        width: 13
    15:
      text:
        label: "Cant. Prod. Term.: "
        align: right
        width: 120
        breakline: 0
        style:
          font_weight: B
    16:
      text:
        field: product_total
        align: left
        width: 50
    17:
      breakline:
    18:
      text:
        label: Detalle Orden de Produccion
        align: center
        style:
          font_size: 12
          font_weight: B
    19:
      table:
        field: results
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          precision: 2
          label: Totales
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
           code:
              label: Codigo
              align: left
              width: 20
          2:
            ingredient:
              label: Materia Prima
              align: left
              width: 50
          3:
            lot:
              label: Lote
              align: left
              width: 20
          4:
           std_kg:
              label: Estandar
              align: right
              width: 35
              unit: Kg
              totalize: true
              precision: 2
          5:
            real_kg:
              label: Real
              align: right
              unit: Kg
              width: 35
              totalize: true
              precision: 2
          6:
            var_kg:
              label: Var Kg
              align: right
              unit: Kg
              width: 30
              totalize: true
              precision: 2
          7:
            var_perc:
              label: Var %
              align: right
              unit: %
              width: 30
              precision: 2
          8:
            hopper:
              label: Tolva
              align: right
              width: 15
    20:
      breakline:
  footer:
    1:
      text:
        label: Reporte generado con Mango v1.0 (Copyleft) 2011
        align: center
        style:
          font_size: 8
          font_color: [80, 80, 80]
