development:
  adapter: mysql2
  database: porcinas_dev
  username: 
  password: 

test:
  adapter: mysql2
  database: porcinas_test
  username: 
  password: 

production:
  adapter: mysql2
  database: porcinas
  username: 
  password: 
